### ISSUE TITLE
Push segue animation is not fluent

### ISSUE THREAD

**Issue by francesc-o** [DevonBoyer/DBProfileViewController#1]
Hi! The controller is very good, but when I tried to push a detail view from profile (with navigation bar), the animation seems to be buggy, it isn't fluent like normally... I tried it on simulator, iPhone and iPad, but nothing change, any suggestion?
Thanks

**Comment by devonboyer** [comment]
Let me give that a try right now and see if I can recreate the issue. I'll get back to you soon!

**Comment by devonboyer** [comment]
I believe your issue is caused by the fact that the viewController's view you are pushing has a clear background (the default) which causes a seemingly buggy push animation. This should fix the push animation. Let me know if this doesn't fix your problem.

`UIViewController *viewController = [[UIViewController alloc] init];`
`viewController.view.backgroundColor = [UIColor whiteColor];` 
`[self.navigationController pushViewController:viewController animated:YES];`

**Comment by francesc-o** [comment]
Yes, the clear background was the problem! Thank you very much

**Comment by devonboyer** [comment]
No problem. Glad you like the controller!
