### ISSUE TITLE
New update has no editProfileButton

### ISSUE THREAD

**Issue by Jackson0111** [DevonBoyer/DBProfileViewController#4]
I did a pod update and saw some changes, everything looks better except I can't call detailsView.editProfileButton any more. And I couldn't find where it is in your code. Help?

**Comment by devonboyer** [comment]
In version 1.0.2 I removed the `editProfileButton`. I mainly had it there for the purposes of the demo since I didn't want the default implementation to include that much detail. The `DBProfileDetailsView` was only intended to be a default implementation with the bare minimum features.

You can however subclass `DBProfileDetailsView` and add in your own `editProfileButton` and then call `profileViewController.detailsView = myDetailsView`. 

Sorry about that, I forgot to mention this change in the CHANGELOG.

**Comment by Jackson0111** [comment]
I see, I will do that then. Thanks!

**Comment by devonboyer** [comment]
I would love to know if you have any new ideas for features or updates. I work on this project frequently, so if you have any more ideas let me know!

**Comment by Jackson0111** [comment]
Sounds great! Good work man

**Comment by Jackson0111** [comment]
So I got the edit profile to work, but now I just discovered a new issue. The cover image is very stretched out, which didn't happen in the previous version. Anything different in the new version that might've changed the behavior?

**Comment by devonboyer** [comment]
Can you describe what you mean by "stretched out"? Are you using `coverPhotoMimicsNavigationBar`?

**Comment by Jackson0111** [comment]
![screen shot 2016-03-21 at 1 02 22 am](https://cloud.githubusercontent.com/assets/13260808/13910959/c020dcd4-ef00-11e5-9935-55352165ec6c.png)
 This is what I see. And yes i am using coverPhotoMimicsNavigationBar

**Comment by devonboyer** [comment]
Oh okay I know what you man. 

The way the cover photo is blurred while scrolling was causing memory warnings to occur too often as well as causing the view take longer to load. 

In version 1.0.2, to fix this problem the cover photo is now cropped to the frame of the cover photo so the image is smaller and therefore faster to add the blur effect. This is why the cover photo may look a little different.

It does appear though that your photo stretched awkwardly a bit, which would mean that the cropping is not happening perfectly.

I can look into adding a property so that this cropping behaviour can be turned off for version 1.0.3.

**Comment by Jackson0111** [comment]
Ok I see. I tried to play around with the coverPhotoView.contentMode, but it didn't work at all.

**Comment by devonboyer** [comment]
Since the image is cropped to the frame of the coverPhoto every contentMode will look the same. 

I will think again about what is the best way to implement this behaviour, simply cropping the photo may not have been the best solution. I will let you know if this changes for version 1.0.3.

Thank you for bringing this up!

**Comment by devonboyer** [comment]
I just pushed version 1.0.3 which includes a property called `shouldCropImageBeforeBlurring` in `DBProfileCoverPhotoView`.

The default is YES. Make sure to set this property BEFORE setting the cover photo in order to give you the result you want.

The demo project now also shows how to use a custom subclass for the `detailsView` as well as how to animate changing the height of the `detailsView` using `beginUpdates` and `endUpdates`.

**Comment by Jackson0111** [comment]
Fantastic!

**Comment by Jackson0111** [comment]
I couldn't do pod update for DBProfileViewController '~>1.0.3' or 1.0.4. The error is : Unable to satisfy the following requirements: - `DBProfileViewController (~> 1.0.3)` required by `Podfile`
